spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  datasource:
    url: jdbc:postgresql://dpg-cj8ivk45kgrc739gm9a0-a.frankfurt-postgres.render.com/notes_db_prod
    username: tw_admin
    password: 9TmPLkbof9mVUDPU4kpVcGMc6yugGEMn
    driver-class-name: org.postgresql.Driver